### ISSUE TITLE
Able to play/discard multiple times using scroll wheel

### ISSUE THREAD

**Issue by HannahBanana1312** [Kooluve/Better-Mouse-And-Gamepad#1]
Scrolling up or down multiple times will play/discard multiple times, leading to strange behavior from the game

discarding multiple times will fill up your hand
![discard](https://github.com/Kooluve/Better-Mouse-And-Gamepad/assets/36461227/83703bb7-1514-44bc-b6fe-57aad463682f)

after you end the round, your deck will be broken
![image](https://github.com/Kooluve/Better-Mouse-And-Gamepad/assets/36461227/86bc94f6-0c48-4ea0-916f-f2fbe363b28a)

cards start to be drawn in broken ways, being flipped and unevenly spaced
![image](https://github.com/Kooluve/Better-Mouse-And-Gamepad/assets/36461227/6895dfa2-be1b-4494-b56f-9f7915efee20)

video of playing hand multiple times
https://github.com/Kooluve/Better-Mouse-And-Gamepad/assets/36461227/e1a23918-d96c-46d2-ba1c-f01bbbfa4301

**Comment by Kooluve** [comment]
Thank you so much! Already fixed in v1.0.1
