### ISSUE TITLE
Crash on discard or play keybind usage

### ISSUE THREAD

**Issue by VivareVeritas** [Kooluve/Better-Mouse-And-Gamepad#3]
Game crashes on discard or play keybind usage

Details:
- repeatable
- happens even when changing "SWAP_MOUSE_WHEEL_WITH_X1_X2 =" is set to true and mouse buttons are used instead of scroll wheel
- No other mods active
- Happens in both Game version 1.0.0n-FULL and 1.0.1c-FULL(public_experimental)
- 0.9.8-STEAMMODDED
- Error Message shown in image

![Screenshot 2024-04-12 155553](https://github.com/Kooluve/Better-Mouse-And-Gamepad/assets/139185544/cfbfb3d6-8c6f-48c8-8a3c-d90e5eafb317)

**Comment by Kooluve** [comment]
Thank you for your feedback. This is mod's own issue, it has been resolved in v1.0.5
